# Generated by Django 3.0.4 on 2020-03-18 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sewfinal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='orderno',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='styleno',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
